# Generated by Django 5.0.5 on 2024-05-07 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_answer_autor_alter_answer_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='teg',
            field=models.CharField(default=datetime.datetime(2024, 5, 7, 13, 4, 49, 320890, tzinfo=datetime.timezone.utc), max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
