# Generated by Django 5.0.5 on 2024-05-07 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_question_teg_alter_question_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
