# Generated by Django 5.0.5 on 2024-05-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='iq',
            field=models.IntegerField(default=7),
        ),
    ]
