# Generated by Django 5.0.5 on 2024-05-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_answer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='rection',
            name='value_no',
        ),
        migrations.RemoveField(
            model_name='rection',
            name='value_yes',
        ),
        migrations.AddField(
            model_name='rection',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
