# Generated by Django 5.0.5 on 2024-05-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_question_answer_remove_rection_value_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rection',
            name='value',
            field=models.IntegerField(),
        ),
    ]
