# Generated by Django 5.0.5 on 2024-05-08 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_rection_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
