# Generated by Django 5.0.5 on 2024-05-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_question_options_alter_rection_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='reactions',
            field=models.ManyToManyField(related_name='answers', to='main.rection'),
        ),
    ]
