# Generated by Django 5.0.5 on 2024-05-24 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_answer_reactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='reactions',
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='main.question'),
        ),
        migrations.AlterField(
            model_name='rection',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rection_set', to='main.answer'),
        ),
    ]
